name: Auto Update Vod

on:
  schedule:
    # 每天北京时间 9 点触发（UTC 1 点）
    - cron: "0 1 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install requests

      # 4. Run Python script
      - name: Run Vod conversion script
        run: |
          python scripts/convert_vod.py

      # 5. Commit and push if changed
      - name: Commit and push if changed
        run: |
          git config --global user.name "137753051@qq.com"
          git config --global user.email "Sherwood1"
          git add vod.json xvod.json
          git diff --quiet && echo "No changes to commit" || (git commit -m "Auto update vod.json and xvod.json" && git push)
