name: Auto Update Vod

on:
  schedule:
    # 每天北京时间 9 点触发（UTC 1 点）
    - cron: "0 1 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests base58

      - name: Run conversion script
        run: python scripts/convert_vod.py

      - name: Update timestamp in update_time.txt # 更新时间
        run: |
          current_time=$(date "+%Y-%m-%d %H:%M:%S")
          echo "Last update: $current_time" > update_time.txt  # 写入最新时间到文件

      - name: Commit and push changes
        run: |
          # 配置 Git 用户信息
          git config --global user.name "137753051@qq.com"
          git config --global user.email "Sherwood1"
          
          # 检查是否有变化，如果有则提交
          git add vod.json xvod.json 20.json 98.json 118.json update_time.txt
          git commit -m "Auto update multiple files with webpage contents"
          git push
