name: Update VOD JSON

on:
  schedule:
    - cron: "0 */6 * * *"  # 每 6 小时自动执行一次
  workflow_dispatch:       # 也可以手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run conversion script
        run: python scripts/convert_vod.py

      - name: Commit and push changes
        run: |
          git config --global user.name "137753051@qq.com"
          git config --global user.email "Sherwood1"
          git add 20.json
          git commit -m "Auto update 20.json from vod.json" || echo "No changes"
          git push
